GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "order pizza"
}

###

DELETE http://localhost:3001/todo/delete/64d1a62f422113d2a59e3d7b

###

PUT http://localhost:3001/todo/complete/64d1a5ed422113d2a59e3d78